image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

cache:
  - /home/appveyor/.gradle

install:
  - java -jar ./artifacts/app-card-delivery.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew dependencies --refresh-dependencies
  - ./gradlew test --info -Dselenide.headless=true