image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

cache:
  - /home/appveyor/.gradle

install:
  - java -jar ./artifacts/app-card-delivery.jar &
  - chmod +x gradlew

environment:
  JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2 -Dfile.encoding=UTF8

build_script:
  - ./gradlew test --info -Dselenide.headless=true