image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

cache:
  - /home/appveyor/.gradle

install:
  # Запускаем SUT в фоне
  - java -jar ./artifacts/app-card-delivery.jar &
  - chmod +x gradlew

build_script:
  # Сначала отдельно подтягиваем зависимости
  - ./gradlew dependencies --refresh-dependencies
  # Потом запускаем тесты
  - ./gradlew test --info -Dselenide.headless=true