plugins {
    id 'java'
}

group = 'ru.netology'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.codeborne:selenide:6.12.4'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
}

test {
    useJUnitPlatform()
}
jar {
    manifest {
        attributes 'Main-Class': 'ru.netology.Application'  // замени на свой главный класс
    }
}