plugins {
    id 'java'
}

group = 'ru.netology'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    // временное зеркало, если есть проблемы с SSL
    maven { url "https://repo.maven.apache.org/maven2/" }
    // или попробуй jcenter() (если проект позволяет)
    // jcenter()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.codeborne:selenide:6.12.4'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
}
dependencies {
    testImplementation 'org.slf4j:slf4j-api:2.0.9'
    testImplementation 'com.codeborne:selenide:6.12.4'
    // остальные твои зависимости (JUnit, JavaFaker, Lombok и т.п.)
}

test {
    useJUnitPlatform()
}
jar {
    manifest {
        attributes 'Main-Class': 'ru.netology.Application'  // замени на свой главный класс
    }
}